import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "@/providers/modal-provider";
import { ToasterProvider } from "@/providers/toast-provider";
import { TransactionModalProvider } from "@/providers/transaction-modal-provider";
import { TransactionsProvider } from "@/contexts/TransactionContext";
import { SupplierModalProvider } from "@/providers/supplier-modal-provider";
import { SuppliersProvider } from "@/contexts/SupplierContext";
import { ProductModalProvider } from "@/providers/product-modal-provider";
import { ProductsProvider } from "@/contexts/ProductContext";
import { SearchProductModalProvider } from "@/providers/search-product-modal-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { StoreModalProvider } from "@/providers/store-modal-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CRM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ToasterProvider />
          <ModalProvider />
          <TransactionModalProvider />
          <ProductModalProvider />
          <SupplierModalProvider />
          <SearchProductModalProvider />
          <TransactionsProvider>
            <StoreModalProvider />
            <ProductsProvider>
              <SuppliersProvider>{children}</SuppliersProvider>
            </ProductsProvider>
          </TransactionsProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
