import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "@/providers/modal-provider";
import { ToasterProvider } from "@/providers/toast-provider";
import { TransactionModalProvider } from "@/providers/transaction-modal-provider";
import { TransactionsProvider } from "@/contexts/TransactionContext";
import { DataCacheProvider } from "@/contexts/DataCacheContext";
import { SupplierModalProvider } from "@/providers/supplier-modal-provider";
import { ProductModalProvider } from "@/providers/product-modal-provider";
import { CashRegisterModalProvider } from "@/providers/cash-register-modal-provider";
import { EditTransactionModalProvider } from "@/providers/edit-transaction-modal-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { StoreModalProvider } from "@/providers/store-modal-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CRM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <DataCacheProvider>
            <ToasterProvider />
            <ModalProvider />
            <TransactionModalProvider />
            <ProductModalProvider />
            <SupplierModalProvider />
            <CashRegisterModalProvider />
            <EditTransactionModalProvider />
            <TransactionsProvider>
              <StoreModalProvider />
              {children}
            </TransactionsProvider>
          </DataCacheProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
